### ISSUE TITLE
Slide-up animation covers the Windows taskbar when using Win10 themes

### ISSUE THREAD

**Issue by ghost** [BoffinbraiN/windows-guification-themes#4] opened 2017-01-30 00:58 UTC
when you use the windows 10/8 theme, it covers the task bar. 
![screenshot 13](https://cloud.githubusercontent.com/assets/25423730/22409768/08739248-e644-11e6-963c-0f820eae5536.png)
This doesn't happen with the other themes

**Comment by BoffinBrain** [comment] 2017-01-30 21:36
Hi starndust31! Are you able to send more screenshots of the issue, and perhaps show more of the desktop? I'm not even able to make out what's what here. If you could use one of the colorful themes too, such as red or blue, that would help. Finally, can you also demonstrate that one of the other WinXP or Win7 themes work correctly under the same configuration?

**Comment by starndust31** [comment] 2017-01-31 02:08
Here's a larger picture of the problem in orange, not sure what the difference is though. I didn't make a video because the notifications have the names of other people I talk to. This is the closing animation of the windows 10 notification.
![screenshot 31](https://cloud.githubusercontent.com/assets/25423730/22449674/7ae0f046-e716-11e6-8a73-c9f7b98484a8.png)
![screenshot 33](https://cloud.githubusercontent.com/assets/25423730/22449675/7aec38f2-e716-11e6-9305-c79b0428bb98.png)
![screenshot 28](https://cloud.githubusercontent.com/assets/25423730/22449562/cbfb0f9e-e715-11e6-90ee-5b9fb36f71fe.png)
This is the closing animation for Win7 notification. (sorry it's in black)
![Uploading vlcsnap-error697.png…]()
Sorry this took a while, I had to wait for a notification to naturally appear and time it right.

**Comment by starndust31** [comment] 2017-01-31 02:13
Shoot, I accidently closed the issue . . . well anyway, the picture for the closing animation for Win 7 notifications didn't upload so I'm going to re upload it
![vlcsnap-error697](https://cloud.githubusercontent.com/assets/25423730/22449863/909dbc7e-e717-11e6-9f08-601bd017bbb1.png)

**Comment by ghost** [comment] 2017-01-31 02:24
Here is the nearly full screen (I cropped the top part because it had my name there), this problem doesn't happen all the time, just at random, but enough to annoy me, so it's a little hard to get a picture, it's a picture of the closing animation for Win10 grey but it looks the same in the other colors so I did what was convenient for me if you don't mind. 
![screenshot 13 _li](https://cloud.githubusercontent.com/assets/25423730/22449993/7b91acf4-e718-11e6-95f5-eb8e233b2ecc.jpg)

Here is a screen shot for win7 closing animation black. It's smoother so it took me a while to make this screenshot.

![vlcsnap-error697](https://cloud.githubusercontent.com/assets/25423730/22450052/f015f5b2-e718-11e6-91ae-dc5acdc08bf3.png)

Also, sorry I accidentally closed this issue.

**Comment by BoffinBrain** [comment] 2017-02-02 00:43
OK, I understand what you're seeing now, and I can also reproduce the issue on Windows 7 with Guifications 2.16. 

The glitchy sliding animation in Guifications is something I've known about for many years, and I actually just turn animations off. Alternatively, you could set the stacking to horizontal instead of vertical.

The difference between the Win7 and other themes is that they have transparency. When I cut out a few transparent pixels in the background.png for one of the Win10 themes, it started behaving like the others.

Take this test image and use it for one of your themes. If that works for you, I may consider redistributing the pack with a whole row/column of transparent pixels to work around the issue. I could also report it to the plugin makers, but I'm not sure if it's still maintained.

![background](https://cloud.githubusercontent.com/assets/13255058/22532615/2de82bda-e8e0-11e6-921c-fffb738bc4c6.png)

If this is really the cause of the issue, I would expect it to occur on most other themes written by others as well, when they use solid background images.

**Comment by ghost** [comment] 2017-02-02 00:56
It works smoothly now, but there's a white dot in the corner. Can you send an image without the white square in the corner?
Thank you.

**Comment by BoffinBrain** [comment] 2017-02-02 21:42
Yes, the transparent hole was just there as a test. Now I know this is a viable workaround, I'll be able to rebuild the Win10 themes with a transparent left edge and update them. I'll do it this weekend!

**Comment by BoffinBrain** [comment] 2017-02-02 21:46
This appears to be the current home for the Guifications plugin: https://bitbucket.org/rw_grim/guifications2 It looks like it's not been touched in a while. If you have a BitBucket account, you could give the developer a poke.

**Comment by BoffinBrain** [comment] 2017-02-08 20:36
Done! Download V1.2.

**Closed as completed by BoffinBrain** 2017-02-08 20:36 UTC
Labels: enhancement
